spring.application.name=banking-app
spring.datasource.url=mysql://localhost:3306/banking_app
spring.datasource.username=root
spring.datasource.password=8235618645
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true